# Generated by Django 4.0.1 on 2024-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
